### ISSUE TITLE
No files

### ISSUE THREAD

**Issue by TriggerMoke** [yameatmeyourdead/Bruhg#2]
Where pickle zac at?

**Comment by yameatmeyourdead** [comment]
I told the witch doctor
I was in love with you
I told the witch doctor
I was in love with you
And then the witch doctor
He told me what to do
He said that
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang...
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang
I told the witch doctor
You didn't love me true
I told the witch doctor
You didn't love me nice
And then the witch doctor
He gave me this advice
He said that
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang...
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang
You've been keeping love from me
Just like you were a miser
And I'll admit I wasn't very smart
So I went out and found myself
A guy that's so much wiser
And he taught me the way to win your heart
My friend the witch doctor
He taught me what to say
My friend the witch doctor
He taught me what to do
I know that you'll be mine
When I say this to you
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang
You've been keeping love from me
Just like you were a miser
And I'll admit I wasn't very smart
So I went out and found myself
A guy that's so much wiser
And he taught me the way to win your heart.
My friend the witch doctor
He taught me what to say
My friend the witch doctor
He taught me what to do
I know that you'll be mine
When I say this to you
Oh Baby
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Come on and...
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla, bing bang
Ooo eee, Ooo ah ah, ting tang
Walla walla bing bang
